CREATE TABLE IF NOT EXISTS  USERS (
  ID               INT         NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME       VARCHAR(50) NOT NULL,
  LAST_NAME        VARCHAR(50) NOT NULL,
  AGE              INT         NOT NULL
);